import 'package:flutter/material.dart';

class MyLocalizations {
  static MyLocalizations of(BuildContext context) {
    return Localizations.of<MyLocalizations>(context, MyLocalizations)!;
  }

  final Map<String, String> _localizedStrings;

  MyLocalizations(this._localizedStrings);

  String translate(String key) {
    return _localizedStrings[key] ?? '';
  }
}

class MyLocalizationsDelegate extends LocalizationsDelegate<MyLocalizations> {
  const MyLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'es'].contains(locale.languageCode);

  @override
  Future<MyLocalizations> load(Locale locale) async {
    if (locale.languageCode == 'es') {
      return MyLocalizations(_localizedStringsSpanish);
    } else {
      return MyLocalizations(_localizedStringsEnglish);
    }
  }

  @override
  bool shouldReload(MyLocalizationsDelegate old) => false;

  static const Map<String, String> _localizedStringsEnglish = {
    'appName': 'CNotes',
    'journal': "Journal",
    'saveS': 'Saved succesfully',
    "actionItems": "Number of Action Items",
    'drawerTracker': 'Tasks',
    'drawerPomodoro': 'Pomodoro',
    'drawerSettings': 'Settings',
    'title': 'Title',
    'duedate': 'Due Date',
    'description': 'Description',
    'category': 'Category',
    'actions': 'Actions',
    'difficulty': 'Difficulty',
    'priority': 'Priority',
    'effort': 'Effort',
    'project': 'Project',
    'projects': 'Projects',
    'tags': 'Tags',
    'add': 'Add',
    'update': 'Update',
    'ideaHintTitle': 'Idea Title',
    'ideaLabeltTitle': 'Title *',
    'ideaValidationtTitle': 'Enter the title',
    'ideaHintDescription': 'Idea Description',
    'ideaLabelDescription': 'Description *',
    'ideaValidationDescription': 'Enter the description',
    'ideaHintNote': 'Extra Note',
    'ideaLabelNote': 'Note *',
    'ideaValidationNote': 'Enter the note',
    'reminderHintTitle': 'Reminder Title',
    'reminderLabeltTitle': 'Title *',
    'reminderValidationtTitle': 'Enter the title',
    'reminderHintDescription': 'Reminder Description',
    'reminderLabelDescription': 'Description *',
    'reminderValidationDescription': 'Enter the description',
    'reminderHintNote': 'Extra Note',
    'reminderLabelNote': 'Note *',
    'reminderValidationNote': 'Enter the note',
    'taskHintTitle': 'Task Title',
    'taskLabeltTitle': 'Title *',
    'taskValidationtTitle': 'Enter the title',
    'taskHintDescription': 'Task Description',
    'taskLabelDescription': 'Description *',
    'taskValidationDescription': 'Enter the description',
    'taskHintPriority': 'Task Priority',
    'taskLabelPriority': 'Select the priority',
    'taskValidationPriority': 'Enter a number',
    'taskHintNote': 'Extra Note',
    'taskLabelNote': 'Note *',
    'taskValidationNote': 'Enter the note',
    'addImage': 'Add Image',
    'processingEntry': 'Processing',
    'work': 'Work',
    'shortRest': 'Short Rest',
    'longRest': 'Long Rest',
    'ended': 'End',
    'start': 'Start',
    'stop': 'Stop',
    'reset': 'Reset',
    'itemValidationDescription': 'You need to enter action tasks',
    'note': 'Note',
    'addNote': 'Enter note',
    'timeDedicated': 'Time dedicated to the task is:',
    'newItem': 'New',
    'noTask': 'No task to work with',
    'noData': 'No data found',
    'settings': 'Settings',
    'workTimeMessage': 'Work Time (minutes)',
    'sRestTimeMessage': 'Short Rest Time (minutes)',
    'lRestTimeMessage': 'Long Rest Time (minutes)',
    'seconds': 'Seconds',
    'ideaDetails': 'Idea Details',
    'close': 'Close',
    'completed': 'Completed',
    'participants': 'Participants',
    'meetings': 'Meetings',
    'content': "Content",
    'status': 'Status',
    'amountactions': 'Amount of actions',
    'idea': "Idea",
    'repeattype': "Frequency",
    'submit': 'Submit',
    'nocompleted': 'Not completed',
    'save': 'Save',
    'reminders': 'Reminder',
    'all': 'All',
    'cweek': 'Current Week',
    'cmonth': 'Current Month',
    'today': 'Today',
    'gnote': 'General Notes',
    'gnotesub': 'Anotate the important stuff',
    'overdue': "Overdue",
    'ideap': "I think",
    'ideapsub1': "therefore",
    'ideapsub2': "I am",
    'catselect': "Select category",
    'tagselectvalid': 'Please select at least one tag',
    'contentadd': 'Enter the content',
    'participantadd': 'Select the participants',
    'dateadd': 'Enter the date',
    'endmeetingadd': 'Enter th end date',
    'daterange': 'End date should be after start date',
    'addaction': 'Add new action',
    'meetingp': 'Meetings',
    'meetingpsub': 'Planification is important',
    'startdate': 'Start date',
    'enddate': 'End date',
    'repeattypeadd': 'Select the frequency',
    'remindermonthcompleted': 'Completed reminders this month',
    'remindermonthnocompleted': 'Remaining reminders this month',
    'allreminder': "All reminders",
    'nextreminder': "Next reminders",
    'taskp': 'My tasks',
    'taskpsub': "Let's start being productive",
    'mid': "Mid effort",
    'lot': "Lot of effort",
    'notmuch': 'Not much effort',
    'difselect': 'Select the difficulty',
    'proselect': 'Select the project',
    'effortselect': 'Select the effort',
    'enterreminder': 'Enter the reminder of the task',
    'localization': 'Localization',
    'noproject':
        'No project to work, please add a new idea of with project as tag',
    'error': "We are sorry, an error has ocurred, please try again later",
    'manage': 'Manage',
    'overview': 'Overview',
    'journalentryofmonthbymood': "Journal entries by mood",
    'frecuencyofentriesinjournal': "Frecuency of entries in the journal",
    "failedlogin": "Failed to login: password or user wrong",
    'welcome': 'Welcome back you\'ve been missed!',
    'username': 'Username',
    'password': 'Password',
    'numoftaskbydiff': 'Number of task by difficulty',
    'numoftaskbyeffort': 'Number of task by effort',
    "timespendmonth": "Total time spend in tasks by month",
    'email': 'Email',
    'number': 'Number',
    'nameValidation': 'Name is required',
    'name': 'Name',
    'pnumber': 'Phone number',
    'pnumberValidation': 'Phone number is required',
    'emailValidator': 'Email is required',
    'contact': 'Contact',
    'routine': 'Routine',
    'people': 'Contacts',
    'ideasub2': 'I am'
  };
  static const Map<String, String> _localizedStringsSpanish = {
    'all': 'Todos',
    'ideasub2': 'I am',
    'routine': 'Rutina',
    'nameValidation': 'El nombre es requerido',
    'contact': 'Contactos',
    'emailValidator': 'Correo es requerido',
    'pnumberValidation': 'El número de teléfono es requerido',
    'email': 'Correo',
    'pnumber': 'Número de teléfono',
    'name': 'Nombre',
    'number': 'Número',
    'contacts': "Contacts",
    'numoftaskbydiff': 'Número de tareas por dificultad',
    "timespendmonth": "Cantidad de tiempo por tarea por mes",
    'numoftaskbyeffort': 'Número de tareas por esfuerzo',
    'username': 'Usuario',
    'password': 'Contraseña',
    'welcome': 'Bienvenido de vuelta, !se te extrañaba!',
    "failedlogin": "Error en login: contraseña o usuario errado",
    'journalentryofmonthbymood': "Entradas del diario por humor",
    'frecuencyofentriesinjournal': "Frecuencia de entradas al diario",
    'manage': 'Administrar',
    'overview': 'Resumen',
    'error': "Lo sentimos, un error ha ocurrido, porfavor intentelo luego",
    'noproject':
        'No hay proyectos para trabajar, cree uno en el apartado de ideas con la etiqueta project',
    'proselect': 'Seleccione el proyecto',
    'localization': 'Lenguage',
    'enterreminder': 'Entre el recordatorio de la tarea',
    'effortselect': 'Seleccione el esfuerzo',
    'difselect': 'Selecciona la dificultad',
    'mid': "Esfuerzo medio",
    'notmuch': 'Poco esfuerzo',
    'lot': "Mucho esfuerzo",
    'taskp': 'Mis tareas',
    'taskpsub': "Empecemos a ser productivos",
    'allreminder': "Todos los recordatorios",
    'nextreminder': "Próximos recordatorios",
    'remindermonthcompleted': 'Recordatorios completados este mes',
    'remindermonthnocompleted': 'Recordatorios restantes este mes',
    'repeattypeadd': 'Seleccione la frecuencia',
    'startdate': 'Fecha de inicio',
    'enddate': 'Fecha de fin',
    'addaction': 'Añada una nueva acción',
    'meetingpsub': 'La planificacion es importante',
    'meetingp': 'Reuniones',
    'dateadd': 'Entre la fecha',
    'daterange': 'La fecha de fin debe ser despues de la fecha de inicio',
    'contentadd': 'Entre el contenido',
    'participantadd': 'Seleccione los participantes',
    'ideap': "Pienso",
    'ideapsub1': "luego",
    'ideapsub2': "existo",
    'tagselectvalid': 'Seleccione un etiqueta mínimo',
    'catselect': "Selecciona la categoría",
    'today': 'hoy',
    'gnote': 'Notas',
    'gnotesub': 'Anota todo lo importante',
    'cweek': 'Semana actual',
    'cmonth': 'Mes actual',
    'overdue': "Atrasados",
    'appName': 'CNotes',
    'journal': 'Diario',
    'reminders': 'Recordatorio',
    'drawerTracker': 'Tareas',
    'saveS': 'Guardado con exito',
    'drawerPomodoro': 'Pomodoro',
    'drawerSettings': 'Opciones',
    'title': 'Título',
    'completed': 'Completado',
    'nocompleted': 'Sin Completar',
    'repeattype': "Frecuencia",
    'amountactions': 'Cantidad de acciones',
    'content': 'Contenido',
    'participants': 'Participantes',
    'duedate': 'Fecha',
    'update': 'Actualizar',
    'description': 'Descripción',
    'category': 'Categoría',
    'actions': 'Acciones',
    'difficulty': 'Dificultad',
    'priority': 'Prioridad',
    'effort': 'Esfuerzo',
    'project': 'Projecto',
    'projects': 'Projectos',
    'tags': 'Tags',
    'add': 'Añadir',
    'noTask': 'No hay tareas para trabajar',
    'idea': "Idea",
    'ideaHintTitle': 'Título de la idea',
    'ideaLabeltTitle': 'Título *',
    'ideaValidationtTitle': 'Entre el título',
    'ideaHintDescription': 'Descripción de la idea',
    'ideaLabelDescription': 'Descripción *',
    'ideaValidationDescription': 'Entre la Descripción',
    'ideaHintNote': 'Nota extra',
    'ideaLabelNote': 'Nota *',
    'ideaValidationNote': 'Entre la nota',
    'reminderHintTitle': 'Título del recordatorio',
    'reminderLabeltTitle': 'Título *',
    'reminderValidationtTitle': 'Entre el título',
    'reminderHintDescription': 'Descripción del recordatorio',
    'reminderLabelDescription': 'Descripción *',
    'reminderValidationDescription': 'Entre la Descripción',
    'reminderHintNote': 'Nota extra',
    'reminderLabelNote': 'Nota *',
    'reminderValidationNote': 'Entre la nota',
    'taskHintTitle': 'Título de la tarea',
    'taskLabeltTitle': 'Título *',
    'taskValidationtTitle': 'Entre el título',
    'taskHintDescription': 'Descripción de la tarea',
    'taskLabelDescription': 'Descripción *',
    'taskValidationDescription': 'Entre la Descripción',
    'taskHintPriority': 'Prioridad de la tarea',
    'taskLabelPriority': 'Seleccione la prioridad',
    'taskValidationPriority': 'Entre una número',
    'taskHintNote': 'Nota extra',
    'taskLabelNote': 'Nota *',
    'taskValidationNote': 'Entre la nota',
    'addImage': 'Añadir imagen',
    'processingEntry': 'Procesando',
    'work': 'Trabajo',
    'shortRest': 'Descanso corto',
    'longRest': 'Descanso largo',
    'start': 'Iniciar',
    'stop': 'Parar',
    'reset': 'Reiniciar',
    'itemValidationDescription': 'Necesita entrar tareas de acción',
    'note': 'Nota',
    'ended': 'Finalizada',
    'addNote': 'Entrar nota',
    'timeDedicated': 'El tiempo dedicado a la tarea es:',
    'newItem': 'Nuevo',
    'noData': 'No se encotró datos',
    'settings': 'Opciones',
    'workTimeMessage': 'Tiempo de trabajo (minutos)',
    'sRestTimeMessage': 'Tiempo de descanso corto (minutos)',
    'lRestTimeMessage': 'Tiempo de descanso largo (minutos)',
    'seconds': 'Segundos',
    'ideaDetails': 'Detalles de la idea',
    'close': 'Cerrar',
    'meetings': 'Reuiniones',
    'status': 'Estado',
    'submit': 'Entrar',
    'save': 'Guardar',
  };
}
